### ISSUE TITLE
Source code license

### ISSUE THREAD

**Issue by machakux** [Alkalit/haystack-elasticsearch5#1]
Hi,

Thanks for working on this backend. Currently it seems like one of the best/simplest options in using Elasticseaech 5.x with Haystack.

What is the license for `haystack-elasticsearch5` ?
Is it going to be released using some standard open source license like MIT, Apache2, BSD, ... etc? .

**Comment by Alkalit** [comment]
I'm sorry that did not pay attention to this question. I think it would be better if this application will be distributed same BSD license as haystask.

https://github.com/Alkalit/haystack-elasticsearch5/blob/master/LICENSE
