### ISSUE TITLE
I installed the relevant elasticsearch5 package and there is retrieval data as 0

### ISSUE THREAD

**Issue by ghost** [Alkalit/haystack-elasticsearch5#3]
![image](https://user-images.githubusercontent.com/29030022/51297857-2960c800-1a5d-11e9-8257-5d4819cc1330.png)
Unable to search any data。
I've tried many times, but it still doesn't work

**Comment by Alkalit** [comment]
Hi, I don't support this package any more. But I can try to help you. You can use the current haystack release - it fully supports ES5

In your project environment remove current installation of haystack
`pip uninstall django-haystack`
and then install the latest release from it's master branch like

`pip install https://github.com/django-haystack/django-haystack/archive/master.zip`

Then in your settings

```
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.elasticsearch5_backend.Elasticsearch5SearchEngine',
        'URL': 'http://127.0.0.1:9200/',
        'INDEX_NAME': 'haystack',
    },
}
```

**Comment by Alkalit** [comment]
Also I would like to advice you do not use haystack - it can be said that it is also does not supported any more or badly supported. Instead I would like suggest you to try `elasticsearch-dsl` package wich is actively supported

**Comment by ghost** [comment]
> Also I would like to advice you do not use haystack - it can be said that it is also does not supported any more or badly supported. Instead I would like suggest you to try `elasticsearch-dsl` package wich is actively supported

Thank you very much. I have used elasticsearch-dsl
